# The Include statement in sshd_config is available since version 8.2: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=631189
---

- name: establish packages
  become: true
  package:
    name: "{{ openssh_packages }}"
    state: present

- name: selinux | allow openssh port
  become: true
  seport:
    ports: "{{ openssh_configuration['Port'] | default(openssh_default_port) }}"
    proto: "tcp"
    setype: "ssh_port_t"
    state: "present"
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"

- name: make run directory
  when: ansible_os_family == "Debian"
  become: true
  file:
    path: "{{ openssh_run_directory }}"
    state: directory
    mode: "u=rwx,go=rx"

- name: Get SSH version
  command:
    argv:
    - bash
    - -c
    - ssh -V 2>&1 | cut -d' ' -f 1 | grep -Eo '[0-9.]+' | head -n 1
  register: ssh_version
# also run this task in check mode:
  check_mode: no

- name: configure openssh
  when: openssh_configuration != {}
  become: true
  template:
    dest: "{{ openssh_configuration_file }}"
    src: "sshd_config.j2"
    mode: "u=rw,go=r"
    owner: root
    group: root
    validate: sshd -f %s -t
  notify:
    - restart openssh

- name: configure match blocks
  when: openssh_configuration == {}
  become: true
  loop: "{{ openssh_configuration_match_blocks | dict2items }}"
  blockinfile:
    path: "{{ openssh_configuration_file }}"
    validate: sshd -f %s -t
    block: |
      Match {{ item.key }}
      {% for k,v in item.items() %}
          {{ k }} {{ v }}
      {% endfor %}
  notify:
    - restart openssh

- name: start and enable the service
  become: true
  service:
    name: "{{ openssh_service }}"
    state: started
    enabled: true
