---

- name: establish packages
  become: true
  package:
    name: "{{ openssh_packages }}"
    state: present

- name: establish run directory
  when: ansible_os_family == "Debian"
  become: true
  file:
    path: "{{ openssh_run_directory }}"
    state: directory
    mode: "u=rwx,go=rx"

- name: generate host keys
  become: true
  command:
    cmd: "ssh-keygen -A"
  changed_when: false

- name: check installed version
  shell: "ssh -V 2>&1"
  register: _openssh_version_output
  changed_when: false
  failed_when: false

- name: establish configuration file directory
  become: true
  file:
    path: "{{ openssh_configuration_file_d }}"
    mode: "u=rwx,go=rx"
    owner: root
    group: root
    state: directory

- name: configure openssh
  loop: "{{ openssh_configuration | default({}) | dict2items }}"
  become: true
  vars:
    content: "{{ item.value }}"
  template:
    dest: "{{ openssh_configuration_file_d }}/{{ item.key }}.conf"
    src: "sshd_config.j2"
    mode: "u=rw,go=r"
    owner: root
    group: root
    validate: /usr/sbin/sshd -f %s -t
  notify:
    - restart openssh

- name: start and enable the service
  become: true
  when: not ansible_check_mode
  service:
    name: "{{ openssh_service }}"
    state: started
    enabled: true
