---

- name: Converge
  hosts: all
  roles:
    - role: ansible-role-openssh
      vars:
        openssh_configuration:
          Port: "22"
        openssh_configuration_match_blocks:
          Address 192.168.1.*:
            PasswordAuthentication: "yes"
            PermitRootLogin: "yes"
